site_name: 程序员代码面试指南-IT名企算法与数据结构题目最优解
site_url: "https://github.com/SourceNote/guide-to-programmer-code-interview"
site_author: Tacey Wong
edit_url: "https://github.com/SourceNote/guide-to-programmer-code-interview/edit/master/contents/"

docs_dir: "contents"

theme: united

nav:
    - 主页: index.md
    - 第一章——栈和队列:
        - "1.设计一个有getMin功能的栈": "01-设计一个有getMin功能的栈/note.md"
        - "2.由两个栈组成的队列": "02-由两个栈组成的队列/note.md"
        - "3.如何仅用递归函数和栈操作逆序一个栈": "03-如何仅用递归函数和栈操作逆序一个栈/note.md"
        - "4.猫狗队列": "04-猫狗队列/note.md"
        - "5.用一个栈实现另一个栈的排序": "05-用一个栈实现另一个栈的排序/note.md"
        - "6.用栈来求解汉诺塔问题": "06-用栈来求解汉诺塔问题/note.md"
        - "7.生成窗口最大值数组": "07-生成窗口最大值数组/note.md"
        - "8.构造数组的MaxTree": "08-构造数组的MaxTree/note.md"
        - "9.求最大子矩阵的大小": "09-求最大子矩阵的大小/note.md"
        - "10.最大值减去最小值小于或等于num的子数组数量": "10-最大值减去最小值小于或等于num的子数组数量/note.md"
    
    - 第二章——链表问题:
        - "1.打印两个有序链表的公共部分": "01-打印两个有序链表的公共部分"
        - "2.在单链表和双链表中删除倒数第K个节点": ""
        - "3.删除链表的中间节点和a/b处的节点": ""
        - "4.反转单向和双向链表": ""
        - "5.反转部分单向链表": ""
        - "6.环形单链表的约瑟夫问题": ""
        - "7.判断一个链表是否为回文结构": ""
        - "8.将单向链表按某值划分成左边小、中间相等、右边大的形式": ""
        - "9.复制含有随机指针节点的链表": ""
        - "10.两个链表生成相加链表": ""
        - "11.两个链表相加的一些列问题": ""
        - "12.将单链表的每个K节点之间逆序": ""
        - "13.删除无序链表中值重复出现的节点": ""
        - "14.在单链表中删除指定值的节点": ""
        - "15.将搜索二叉树转换成双向链表": ""
        - "16.单链表的选择排序": ""
        - "17.一种怪异的节点删除方式": ""
        - "18.向有序的环形单链表中添加新节点": ""
        - "19.合并两个有序的单链表": ""
        - "20.按照左右半区的方式重新组合单链表": ""
    - 第三章——二叉树问题:
        - "1.分别递归和非递归方式实现二叉树先中后序遍历": ""
        - "2.打印二叉树的边界节点": ""
        - "3.如何较为直观地打印二叉树": ""
        - "4.二叉树的序列化和反序列化": ""
        - "5.遍历二叉树的神级方法": ""
        - "6.在二叉树中找到累加和为指定值的最长路径长度": ""
        - "7.找到二叉树的最大搜索二叉子树": ""
        - "8.找到二叉树中符合搜索二叉树条件的最大拓扑结构": ""
        - "9.二叉树的按层打印和ZigZag打印": ""
        - "10.调整搜索二叉树中两个错误的节点": ""
        - "11.判断t1树是否包含t2树全部的拓扑结构": ""
        - "12.判断t1树是否有与t2树拓扑结构万全相同的子树": ""
        - "13.判断二叉树是否为平衡二叉树": ""
        - "14.根据后序数组重建搜索二叉树": ""
        - "15.判断一棵二叉树是否为搜索二叉树和完全二叉树": ""
        - "16.通过有序数组生成平衡搜索二叉树": ""
        - "17.在二叉树中找到一个节点的后继节点": ""
        - "18.在二叉树中找到两个节点的最近公共祖先": ""
        - "19.Tarjan算法与并查集解决二叉树节点间最近公共祖先的批量查询问题": ""
        - "20.二叉树节点间的最大距离问题": ""
        - "21.先中后序数组两两结合重构二叉树": ""
        - "22.通过先序数组和中序数组生成后序数组": ""
        - "23.统计和生成所有不同的二叉树": ""
        - "24.统计完全二叉树的节点数": ""

    
    - 第四章——递归和动态规划:
        - "1.斐波那契系列问题的递归和动态规划": ""
        - "2.矩阵的最小路径和": ""
        - "3.换钱的最小货币数": ""
        - "4.换钱的方法数": ""
        - "5.最长递增子序列": ""
        - "6.汉诺塔问题": ""
        - "7.最长公共子序列问题": ""
        - "8.最长公共子串问题": ""
        - "9.最小编辑代价": ""
        - "10.字符串的交错组成": ""
        - "11.龙与地下城游戏问题": ""
        - "12.数字字符串转换为字母组合的种数": ""
        - "13.表达式得到期望结果的组成种数": ""
        - "14.排成一条线的纸牌博弈问题": ""
        - "15.跳跃游戏": ""
        - "16.数组中的最长连续序列": ""
        - "17.N皇后问题": ""

    - 第五章——字符串问题:
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""
        - "": ""

    - 第六章——大数据和空间限制
        - "": ""

    - 第七章——位运算
        - "": ""

    - 第八章——数组和矩阵问题
        - "": ""

    - 第九章——其他题目
        - "": ""

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists



别怀疑，画面没动

为啥没动

单身狗不敢出镜啊！！！！无限怨念啊！！！！！

